image: ruby:2.4.2

stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: 'mongo:27017'

build_job:
  stage: build
  image: docker:19.03.6
  services:
    - name: docker:19.03.6-dind
    - alias: docker
  before_script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
  script:
    - cd reddit
    - bundle install

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'
