dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: an7sUmXTo4en05vDAS1pPF74CD0iRDS0EgIS0sU98sFbxYLIh8mOJwTvwyLtjAylfExbENZGoZCJTku2jfKjKZmDYlb2vUIZIBdTInY3O3o0VDOb30ziuAgXuhEKoackclWq9v5pdnDmhUIP3m8okEVliIWBcaMtICi+/Nt+IgdwwojpZWQAoJrB6zcFLFuWMOuB5UMebwaYBBkA0bE9+txMm9HO+w1CLH5e7OO9/7oU1k7hpTPGMa5XWVJADU0Cx7Dm1Xx08AqF8EvHTNsXF3mOPCYGiwVq7m08ISy8QFVFHB4mW0c1fjN92jB1X5ASNfVqPdCnf1EFlxR7t7svNqpLZTd9uF5vH0zAwag9uC7sljyu/bw060gaYmaPap7DfgyfWVvOUPcnmgvUHzLf9O2JrOfHxyWglK+KEIkFwsyptj9dhyElDyBSHFeQoVwNjCXC9ArFoyxAqzGZ1CiNXPxxArtbQRV4S2zLzJy/h+vVfNxg18C1HC9SFu8x58VTUmpzJ9XTyXDVs/lqcijN6ZL0ntcS+0GCgY1RQr3bRKVLZI1mjYrAAKgnyvUINuMO/7i4SdP2XE3ebcOhd4b9j8dYncElo2mJmbaKOzOjafiuOP49lx8E+3AXMvGPyYuBcHXcU8RmB6fqfFSk2q3dkS6bmwJVkFpZMpwTlmsbkGY=
