dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: YfU/56DsTQwAl6anZ4vhNlrstrVXxc1JDBbn2hSMCjP2FJ/a8G394xwqYoWLJECb8ItaYlpyWlvv1ew4b5V6Dl0gn5oOFdga+EmYz30QcpMYD7LMKqX8CBPTAmcWMHnxGUXBvvq1RjZ5xFdZeaWbOqu7owDMFbRO5DgL7bkuO35E2wFFAbQt48gUYRPwuMYnKm/ifwvpp9eNEpjjPT6Ofzbcl5U4CPsnEK1XYIJz1J9sbOLprWPchuRj7fcigG7OemfP3W7UG1B1IXFdW1XMRyoReeuBYPl9bqvCEBhtuzzlZ0oaPVxtEJFX9qUIRBQw8oT7NwvvJyuxD9fDg9qQxXF1yDy52lDwfCTA1yZb1PDEkP4gzNMQdLRlRliM3eDFiIagkBStP0Tt2N9UtIaxTh1sDtLWMVMb+XWqzbtQliOyYm4Sn5jIuGPw3AfF0fjIktPlmtCBrrZGxCElzACp/J1t+SJFbv5c4u1L7dR5U0lYrjgmMJFkM8xDqr7HKPqD9fHb8nBRPT99hhH2GGuWoeZP3CtC9XTKZN3ETjyf9jiSxcJ9iZJkBqf6/2syp0tpXD+vw5jjm9DW/XniEpMtxFvWNWeUQigcy/QyqsCGx1dzsAL/55N28WltoHPSB+R8lydwx3OOL8c3suhvTYZokSM+EpSCRDNVOLPXoKDNbms=
