dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: DM5H+d+vTC9u6QC0LNPjAOAtaTctnkod6v4y/GA5TRdedMhnZ1BaONeWkxfZ0HZ1Wtg7+NRoFwLfRabl/GlDUkyhZHCozpTIpUHjYDHqy2AREH2GxDxivGr0mezUsZvU71SBap3c+VlhCuS56NP+VqsOdcU/RW7dvDG44xOZYyByBAFJKKw4RYoNjeTQWyfLLs+++asILRLtrlET8vipsVuTwTv/Wo9QG/j0Zd4pdN8DxmqavgPbPBfxWqrhARFY2RGKrHh63iS4vU7NkcUDUAw/6pR7Q2TzdzSSarH5LPpEiiomd60NeKFWlPPX1YftSgI5Cn7h6BOXWHNfndCDJ+78ksSCzOzItAHv6nJ9+xdzwppl5PZxDsiT7HaGBRNXwK28qcm9bd/0tF/xUOUj/1rUQJ/JiYscsDYmYFDJmAlNtCsTZo7+9wEdN1ZD1PALcCVzxPdrU7+hHbP9Fp/PY3EaGH8ERCB6ZW+zSgoImxhfv6sAJre1Wn2Nap8pnGiTptGJ9qMJz8yQwY2LykdLQNWi256f3mDOaXPU4ebDEzkw2KwOr7iFIC+VFbBjzRea/xuVgc0onsGroa5RUYLm603Y4QZLZIoS5PazGod/5+L6wwIwXwEKeMBiLQIqsw/491tsJ3RIgQYIEhTXnEYwzHX8JWMD3LbHeS+oGkCI2m8=
