---
    - name: Deploy App
      hosts: all
      become: true
      tags: deploy

      tasks:

        - name: Pull docker image
          docker_image:
            name: asurygin/otus-reddit:1.0
            source: pull
            state: present

        - name: Create docker container
          docker_container:
            name: reddit
            image: asurygin/otus-reddit:1.0
            detach: yes
            state: started
            published_ports:
              - 80:9292
