---
    - name: Install docker
      hosts: all
      become: true
      tags: install

      tasks:
        - name: Install aptitude using apt
          apt:
            name:
              - aptitude
              - python-pip
            state: latest
            update_cache: yes
            force_apt_get: yes

        - name: Add apt key
          become: true
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add apt repository and update cache
          become: true
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu xenial stable
            state: present
            update_cache: yes

        - name: Install docker
          become: true
          apt:
            name:
             - docker.io
             - docker-compose
            state: present

        - name: Install Docker Module for Python
          pip:
            name: docker
            executable: pip

        - name: Start docker unit
          systemd:
            name: docker
            state: started
            enabled: yes

        - name: Creates directory Gitlab
          file:
            path: "{{ item }}"
            state: directory
          loop:
            - /srv/gitlab/config
            - /srv/gitlab/data
            - /srv/gitlab/logs
            - /srv/gitlab-runner/config
