version: '3.3'
services:
  post_db:
    restart: always
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    restart: always
    ports:
      - ${PORT_APP}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    restart: always
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    restart: always
    networks:
      - front_net
      - back_net

volumes:
  post_db:


networks:
  front_net:
  back_net:
