cloud_id                 = "b1gfndo9d7vsl5mvgp7k"
folder_id                = "b1goa6g1vaq7972e9an1"
zone                     = "ru-central1-b"
image_id                 = "fd83bj827tp2slnpp7f0"
public_key_path          = "~/.ssh/yc_rsa.pub"
private_key_path         = "~/.ssh/yc_rsa"
subnet_id                = "e2liuhltqcg482aob07o"
service_account_key_file = "~/Gitlab/terraform-key.json"
